# -*- coding: utf-8 -*-
"""Untitled194.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Jnpk-Sf5WW6EUtdlm2J0HHLr02TLreun

#**CSV Data Exploration & Visualization**
"""

# Importing required libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Loading csv file
df = pd.read_csv('electricity_demand.csv')

# Displaying first 10 rows
df.head(10)

# Displaying Shape of the dataset
df.shape

# Displaying column names
df.columns

# Displaying data types of each column
df.dtypes

# Getting only numeric columns
numeric_cols = df.select_dtypes(include=['number']).columns

# Displaying numeric columns
numeric_cols

# Doing .describe() for numeric columns.
df[numeric_cols].describe()

# Checking null values in each column
df.isna().sum()

# Filling mean values
df.fillna(df.mean(numeric_only=True), inplace=True)

# Checking for any null values after filling mean values
df.isna().sum()

df.head()

# Filtering rows (1)
df.loc[df['Humidity'] > 50]

# Filtering rows (2)
df.loc[df['year']== 2020]

# Sorting the dataset by column 'Demand' in descending order.
df.sort_values(by='Demand', ascending=False)

# Grouped by column 'Timestamp'(Not a numeric) and calculated mean of column 'Demand'(Numeric)
df_grouped = df.groupby('Timestamp')['Demand'].mean().reset_index()

# Displaying grouped and aggregated values
df_grouped

# Histogram for numeric column
plt.hist(df['Demand'], bins=30, edgecolor='black')
plt.title('Histogram of Demand')
plt.xlabel('Demand')
plt.ylabel('Frequency')
plt.show()

# Bar chart
df.head()

grouped_1 = df.groupby('Timestamp')['Temperature'].mean()

plt.bar(grouped_1.index, grouped_1.values)
plt.title('Timestamp vs Temperature')
plt.xlabel('Timestamp')
plt.ylabel('Temperature')
plt.show()

